numpy: '1.11'
perl: '5.26'
lua: '5'
r_base: '3.4'
cpu_optimization_target: nocona
target_platform: win-32
MACOSX_DEPLOYMENT_TARGET: '10.9'
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
blas_impl: mkl
boost: '1.64'
bzip2: '1.0'
cairo: '1.14'
cross_compiler_target_platform: win-64
dbus: '1'
expat: '2.2'
fontconfig: '2.12'
fortran_compiler: intel-fortran
freetype: '2.8'
geos: 3.6.0
giflib: '5.1'
glib: '2.53'
gst_plugins_base: '1.12'
gstreamer: '1.12'
harfbuzz: '1.5'
hdf4: '4.2'
hdf5: '1.10'
icu: '58'
jpeg: '9'
libdap4: '3.19'
libgdal: '2.2'
libkml: '1.3'
libnetcdf: '4.4'
libpng: '1.6'
libtiff: '4.0'
libxml2: '2.9'
lzo: '2'
macos_machine: x86_64-apple-darwin13.4.0
macos_min_version: '10.9'
mkl: '2018'
openblas: 0.2.19
openjpeg: '2.2'
openssl: 1.0.2
pixman: '0.34'
proj4: '4'
scipy: '0.19'
sqlite: '3'
tk: '8.6'
xz: '5'
zlib: '1.2'
zip_keys:
- !!python/tuple [vc, c_compiler, cxx_compiler, fortran_compiler_version, python,
  ipython]
pin_run_as_build:
  libboost:
    max_pin: x.x
  python:
    max_pin: x.x
    min_pin: x.x
c_compiler: vs2015
python: '3.6'
vc: '14'
ipython: '6.1'
cxx_compiler: vs2015
fortran_compiler_version: 16.0.4
